---
# tasks file for docker
- name: Update package cache and install dependencies
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Update package cache after adding Docker APT repository
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: "{{ item }}"
    state: present
  loop: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
- name: Creates directory
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d/
    state: directory

- name: copy config file 
  ansible.builtin.copy:
    src: override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf

- name: Restart service docker
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: docker