---
#tasks file for docker
- name: Update /etc/resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver {{ item.nameserver }}'
    state: '{{ item.state }}'
  loop:
    - { nameserver: 10.202.10.102, state: present }
    - { nameserver: 10.202.10.202, state: present }
    - { nameserver: 1.1.1.1, state: absent }
    - { nameserver: 8.8.8.8, state: absent }
  tags: filternet

- name: Uninstall all conflicting packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent


- name: Update package cache and install dependencies
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg

- name: Add apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Update package cache after adding Docker APT repository
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Creates directory
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d/
    state: directory

- name: Add Docker daemon configuration file
  ansible.builtin.copy:
    content: |
      {
       "insecure-registries" : ["https://{{ docker_registry }}"],
       "registry-mirrors": ["https://{{ docker_registry }}"],
       "metrics-addr" : "0.0.0.0:9323",
       "experimental" : true
      }
    dest: /etc/docker/daemon.json
    mode: "0644"
  notify: Restart Docker daemon
  tags: filternet


